-- Risk Matrix Mapping (Standar Warna)
INSERT INTO risk_matrix_mapping (risk_value, frequency, impact, category, color_code, description, mitigation_level) VALUES
(1, 1, 1, 'Biru', '#0066CC', 'Risiko Rendah', 'Low'),
(2, 1, 2, 'Biru', '#0066CC', 'Risiko Rendah', 'Low'),
(3, 1, 3, 'Biru', '#0066CC', 'Risiko Rendah', 'Low'),
(5, 1, 5, 'Hijau', '#00CC00', 'Risiko Sedang Rendah', 'Low-Medium'),
(6, 2, 3, 'Hijau', '#00CC00', 'Risiko Sedang Rendah', 'Low-Medium'),
(8, 2, 4, 'Hijau', '#00CC00', 'Risiko Sedang Rendah', 'Low-Medium'),
(10, 2, 5, 'Kuning', '#FFFF00', 'Risiko Sedang', 'Medium'),
(11, 1, 11, 'Kuning', '#FFFF00', 'Risiko Sedang', 'Medium'),
(13, 1, 13, 'Kuning', '#FFFF00', 'Risiko Sedang', 'Medium'),
(14, 2, 7, 'Kuning', '#FFFF00', 'Risiko Sedang', 'Medium'),
(16, 2, 8, 'Jingga', '#FF9900', 'Risiko Tinggi', 'High'),
(17, 1, 17, 'Jingga', '#FF9900', 'Risiko Tinggi', 'High'),
(18, 3, 6, 'Jingga', '#FF9900', 'Risiko Tinggi', 'High'),
(19, 1, 19, 'Jingga', '#FF9900', 'Risiko Tinggi', 'High'),
(20, 4, 5, 'Jingga', '#FF9900', 'Risiko Tinggi', 'High'),
(21, 3, 7, 'Merah', '#FF0000', 'Risiko Sangat Tinggi', 'Critical'),
(22, 2, 11, 'Merah', '#FF0000', 'Risiko Sangat Tinggi', 'Critical'),
(23, 1, 23, 'Merah', '#FF0000', 'Risiko Sangat Tinggi', 'Critical'),
(24, 4, 6, 'Merah', '#FF0000', 'Risiko Sangat Tinggi', 'Critical'),
(25, 5, 5, 'Merah', '#FF0000', 'Risiko Sangat Tinggi', 'Critical');

-- Insert 26 Risk Indicators
INSERT INTO risk_indicators (indicator_code, indicator_name, indicator_description, indicator_type, pic_section, p26_initial, r26_target, effective_quarter, effective_year) VALUES
('1a-CP-01', 'Nilai Kinerja Pelaksanaan Anggaran K/L', 'Satker tidak valid dalam mengisi capaian output', 'IKU', 'Seksi MSKI', 14, 10, 'Q1', 2024),
('1a-CP-02', 'Nilai Kinerja Pelaksanaan Anggaran K/L', 'Rendahnya nilai kualitas pelaksanaan anggaran', 'IKU', 'Seksi MSKI', 19, 16, 'Q1', 2024),
('1a-CP-03', 'Nilai Kinerja Pelaksanaan Anggaran K/L', 'Satker terlambat menyampaikan pertanggungjawaban UP/TUP', 'IKU', 'Seksi MSKI', 19, 15, 'Q1', 2024),
('2a-CP-01', 'Indeks Kepuasan terhadap Layanan KPPN', 'Edukasi dan komunikasi yang tidak optimal', 'IKU', 'Seksi MSKI', 13, 10, 'Q1', 2024),
('2a-CP-02', 'Indeks Kepuasan terhadap Layanan KPPN', 'Respon atas pertanyaan/konsultasi tidak tepat waktu', 'IKU', 'Seksi MSKI,Subbagian Umum', 16, 15, 'Q1', 2024),
('3a-CP-01', 'Indeks Kinerja Penyaluran Dana Transfer ke Daerah pada KPPN', 'TKD tidak disalurkan tepat waktu', 'IKU', 'Seksi Bank', 16, 15, 'Q1', 2024),
('3b-N-01', 'Indeks Kualitas Penyelesaian SP2D dan Akurasi Perencanaan Kas', 'Waktu pengajuan SPM tidak sesuai RPD', 'Non-IKU', 'Seksi MSKI,Seksi PD', 17, 13, 'Q1', 2024),
('3b-N-02', 'Indeks Kualitas Penyelesaian SP2D dan Akurasi Perencanaan Kas', 'Penyelesaian SP2D lebih dari 1 jam', 'Non-IKU', 'Seksi PD', 17, 13, 'Q1', 2024),
('3b-N-03', 'Indeks Kualitas Penyelesaian SP2D dan Akurasi Perencanaan Kas', 'Bertambahnya jumlah retur', 'Non-IKU', 'Seksi PD', 22, 16, 'Q1', 2024),
('3b-N-04', 'Indeks Kualitas Penyelesaian SP2D dan Akurasi Perencanaan Kas', 'Penyelesaian retur tidak tepat waktu', 'Non-IKU', 'Seksi Vera', 14, 10, 'Q1', 2024),
('4a-N-01', 'Indeks Akuntabilitas Pelaporan Keuangan Satker', 'Keterlambatan LPJ bendahara oleh bendahara K/L', 'IKU', 'Seksi Vera', 16, 15, 'Q1', 2024),
('4a-N-02', 'Indeks Akuntabilitas Pelaporan Keuangan Satker', 'Terdapat satuan kerja yang terlambat tutup periode permanen', 'IKU', 'Seksi Vera', 16, 15, 'Q1', 2024),
('5a-N-01', 'Tingkat Kualitas Pengelolaan Kinerja Organisasi', 'Kurang optimalnya pimpinan unit dalam mengimplementasikan prinsip-prinsip SFO', 'Non-IKU', 'Subbagian Umum', 17, 10, 'Q1', 2024),
('6a-CP-01', 'Indeks Kualitas Pengelolaan Keuangan, BMN, Pengadaan, dan Arsip', 'Kualitas LK tingkat UAKPA dan UAKPB tidak maksimal', 'IKU', 'Subbagian Umum', 17, 10, 'Q1', 2024),
('6a-CP-02', 'Indeks Kualitas Pengelolaan Keuangan, BMN, Pengadaan, dan Arsip', 'Kebakaran gedung kantor', 'IKU', 'Subbagian Umum', 16, 15, 'Q1', 2024),
('6a-CP-03', 'Indeks Kualitas Pengelolaan Keuangan, BMN, Pengadaan, dan Arsip', 'Penerapan gedung ramah lingkungan', 'IKU', 'Subbagian Umum', 13, 17, 'Q1', 2024),
('6a-CP-04', 'Indeks Kualitas Pengelolaan Keuangan, BMN, Pengadaan, dan Arsip', 'Kerusakan BMN', 'IKU', 'Subbagian Umum', 14, 11, 'Q1', 2024),
('6b-N-01', 'Nilai Kinerja TIK Kanwil DJPb', 'Penyalahgunaan user aplikasi KemenKeu oleh pihak yang tidak berwenang', 'Non-IKU', 'Subbagian Umum', 13, 10, 'Q1', 2024),
('NON-IKU-01', 'Penguatan fungsi kehumasan media dan kehumasan lembaga KPPN sebagai financial advisory', '', 'Non-IKU', 'Subbagian Umum', 17, 22, 'Q1', 2024),
('NON-IKU-02', 'Penggunaan website kantor sebagai media penyebarluasan informasi', '', 'Non-IKU', 'Subbagian Umum', 16, 22, 'Q1', 2024),
('NON-IKU-03', 'Potensi moral hazard oleh satker pada aplikasi gaji dan tukin', '', 'Non-IKU', 'Seksi MSKI', 19, 15, 'Q1', 2024),
('MANDATORY-01', 'Persepsi negatif masyarakat atas pemberitaan di media massa dan media sosial', '', 'Mandatory', 'Subbagian Umum,Seksi MSKI', 22, 15, 'Q1', 2024),
('MANDATORY-02', 'Ownership pegawai terhadap organisasi', '', 'Mandatory', 'Seksi MSKI', 22, 15, 'Q1', 2024),
('MANDATORY-03', 'Adanya perilaku korupsi pada pegawai', '', 'Mandatory', 'Seksi MSKI', 16, 15, 'Q1', 2024),
('MANDATORY-04', 'Kebocoran data dan informasi terkait konfidensial/rahasia', '', 'Mandatory', 'Subbagian Umum,Seksi MSKI', 16, 15, 'Q1', 2024),
('2b-N-01', 'Tingkat Implementasi Penajaman Tugas Financial Advisory', '', 'Non-IKU', 'Seksi MSKI', NULL, NULL, 'Q1', 2024),
('3c-N-01', 'Indeks Digitalisasi Pengelolaan Keuangan', '', 'Non-IKU', 'Seksi MSKI', NULL, NULL, 'Q1', 2024),
('5b-N-01', 'Nilai Kualitas Pengelolaan SDM', '', 'Non-IKU', 'Subbagian Umum', NULL, NULL, 'Q1', 2024),
('5c-N-01', 'Nilai Hasil Evaluasi Pelaksanaan Tugas Kepatuhan Internal', '', 'Non-IKU', 'Subbagian Umum', NULL, NULL, 'Q1', 2024);
